import { Sen } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// theme provider
import { ThemeProvider } from "@/components/ThemeProvider";

const josef = Sen({
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
   display: "swap" 
  
  });

export const metadata = {
  title: "Elegant Dwell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={josef.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header />
            {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
